name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present

  setup:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Chromium
      uses: browser-actions/setup-chromium@latest
    - run: npm install selenium-webdriver express mocha webdriver-manager
    - run: ./node_modules/.bin/webdriver-manager update --versions.chrome=89.0.4389.23
    - run: node server.js &

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx mocha test/test.spec.js
      env:
        CI: true
